# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sudentname',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sudent_name', models.CharField(max_length=50)),
                ('sudent_name_new', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '17_sudentname',
            },
        ),
    ]
