# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sudentname',
            options={'verbose_name': '2017年学生注册信息表'},
        ),
        migrations.AlterField(
            model_name='sudentname',
            name='sudent_name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='sudentname',
            name='sudent_name_new',
            field=models.CharField(max_length=50, verbose_name='新增姓名'),
        ),
    ]
