# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfo', '0003_auto_20180924_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalexam',
            fields=[
                ('success_id', models.AutoField(primary_key=True, serialize=False)),
                ('sudent_schoolid', models.PositiveIntegerField(default=0, verbose_name='学号')),
                ('sudent_classid', models.PositiveSmallIntegerField(default=0, verbose_name='班级')),
                ('chitotal', models.FloatField(default=0, verbose_name='语文总分')),
                ('mattotal', models.FloatField(default=0, verbose_name='数学总分')),
                ('engtotal', models.FloatField(default=0, verbose_name='英语总分')),
                ('phytotal', models.FloatField(default=0, verbose_name='物理总分')),
                ('chetotal', models.FloatField(default=0, verbose_name='化学总分')),
                ('orgtotal', models.FloatField(default=0, verbose_name='生物总分')),
                ('poltotal', models.FloatField(default=0, verbose_name='政治总分')),
                ('histotal', models.FloatField(default=0, verbose_name='历史总分')),
                ('geototal', models.FloatField(default=0, verbose_name='地理总分')),
                ('Artsubjecttotal', models.FloatField(default=0, verbose_name='文科总分')),
                ('Scisubjecttotal', models.FloatField(default=0, verbose_name='理科总分')),
                ('chiurbrank', models.PositiveIntegerField(default=0, verbose_name='语文单科联考排名')),
                ('maturbrank', models.PositiveIntegerField(default=0, verbose_name='数学单科联考排名')),
                ('engurbrank', models.PositiveIntegerField(default=0, verbose_name='英语单科联考排名')),
                ('phyurbrank', models.PositiveIntegerField(default=0, verbose_name='物理单科联考排名')),
                ('cheurbrank', models.PositiveIntegerField(default=0, verbose_name='化学单科联考排名')),
                ('orgurbrank', models.PositiveIntegerField(default=0, verbose_name='生物单科联考排名')),
                ('polurbrank', models.PositiveIntegerField(default=0, verbose_name='政治单科联考排名')),
                ('hisurbrank', models.PositiveIntegerField(default=0, verbose_name='历史单科联考排名')),
                ('geourbrank', models.PositiveIntegerField(default=0, verbose_name='地理单科联考排名')),
                ('Artsubjecturbrank', models.PositiveIntegerField(default=0, verbose_name='文科总分联考排名')),
                ('Scisubjecturbrank', models.PositiveIntegerField(default=0, verbose_name='理科总分联考排名')),
                ('finalexamnum', models.PositiveSmallIntegerField(default=0, verbose_name='考试编号')),
            ],
            options={
                'verbose_name': '2017届学生各学期期考成绩汇总表',
                'db_table': '17_sudentfinalexam',
            },
        ),
        migrations.CreateModel(
            name='monthlyexam',
            fields=[
                ('success_id', models.AutoField(primary_key=True, serialize=False)),
                ('sudent_schoolid', models.PositiveIntegerField(default=0, verbose_name='学号')),
                ('sudent_classid', models.PositiveSmallIntegerField(default=0, verbose_name='班级')),
                ('chitotal', models.FloatField(default=0, verbose_name='语文总分')),
                ('mattotal', models.FloatField(default=0, verbose_name='数学总分')),
                ('engtotal', models.FloatField(default=0, verbose_name='英语总分')),
                ('phytotal', models.FloatField(default=0, verbose_name='物理总分')),
                ('chetotal', models.FloatField(default=0, verbose_name='化学总分')),
                ('orgtotal', models.FloatField(default=0, verbose_name='生物总分')),
                ('poltotal', models.FloatField(default=0, verbose_name='政治总分')),
                ('histotal', models.FloatField(default=0, verbose_name='历史总分')),
                ('geototal', models.FloatField(default=0, verbose_name='地理总分')),
                ('Artsubjecttotal', models.FloatField(default=0, verbose_name='文科总分')),
                ('Scisubjecttotal', models.FloatField(default=0, verbose_name='理科总分')),
                ('finalexamnum', models.PositiveSmallIntegerField(default=0, verbose_name='考试编号')),
            ],
            options={
                'verbose_name': '2017届学生各学期月考成绩汇总表',
                'db_table': '17_sudentmonthlyexam',
            },
        ),
        migrations.CreateModel(
            name='Sclassname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sclass_id', models.PositiveIntegerField(default=0, verbose_name='班级ID')),
                ('Sclass_name', models.CharField(default=0, max_length=50, verbose_name='班级名称')),
                ('Sclass_category', models.CharField(default=0, max_length=50, verbose_name='班级文理分类')),
                ('Sclass_type', models.CharField(default=0, max_length=50, verbose_name='班级成绩分类')),
                ('Sclass_introduction', models.CharField(default=0, max_length=50, verbose_name='班级所在阶段')),
                ('Sclass_Abbreviations', models.CharField(default=0, max_length=50, verbose_name='班级阶段简写')),
            ],
            options={
                'verbose_name': '2017届各班级基本信息表',
                'db_table': '17_sudentclassname',
            },
        ),
        migrations.AlterModelOptions(
            name='sudentname',
            options={'verbose_name': '2017届学生注册信息表'},
        ),
    ]
